### ISSUE TITLE
please make the value in the status bar selectable 

### ISSUE THREAD

**Issue by paulle** [dubrowgn/wattz#15]
Hello maybe you can make the value in status bar selectable, for choosing if it shows Watt or battery temperature in F° or C°
Sometimes this is very useful when the battery is getting hot.

**Comment by dubrowgn** [comment]
I'll think about it. I wanted to keep the app as simple as possible, but with the recent addition of the settings page, this might be possible. Were you thinking of having one configurable indicator, or multiple indicators?

**Comment by paulle** [comment]
Gesendet von Proton Mail für Mobilgeräte

I don't know what's better for you
to handle. I believe one configurable would be sufficient.
If it's easier for you multiple indicators would be fine too.
Thank you for your nice app.

-------- Original-Nachricht --------
Am 3. Okt. 2022, 22:39, schrieb Dustin Brown :

**Comment by paulle** [comment]
Even the value in the status bar is hard to read, very tiny font.
Maybe for better readability it would be better to show the unit not beneath value, showing the unit aside the value would it make less hard to read .

**Comment by dubrowgn** [comment]
The status bar icon is unfortunately width constrained. Removing the units wouldn't actually allow us to make the font bigger. Sorry :/

**Comment by paulle** [comment]
Ok, I didn't knew this. Excuse me.

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 4. Okt. 2022, 16:50, schrieb Dustin Brown :

**Comment by bdantas** [comment]
I love your app. Thanks to the workaround in settings, it is the only one that seems to get accurate data from my aftermarket battery.

App would be most useful to me if status bar could show energy (Wh) instead of power (W). My OS's (LineageOS) battery indicator always shows 100% for this battery while your app's energy reading is accurate.

Pretty please make the value in status bar selectable so that showing only energy (Wh) is possible.

**Comment by mv1005** [comment]
Hi there, thanks for that simple but yet useful app. I also would appreciate having a configurable value in the status bar. In my case, I would like to watch battery voltage.

**Comment by dubrowgn** [comment]
Release https://github.com/dubrowgn/wattz/releases/tag/v1.13 added a status bar indicator units setting. It should show up in F-Droid in the next few days. Google Play is a different story due to new changes to their publishing requirements, so no ETA there at the moment. I'm going to close this as resolved, but feel free to provide feedback.
