### ISSUE TITLE
feature request: charging current

### ISSUE THREAD

**Issue by ulph0** [dubrowgn/wattz#16]
hi, i looked for a free app like "ampere"where you can see how much current your mobiile gets from the charger. at least an approximate value so you can see the charger has the power it promises. i thought wattz has ist, but it doesn't maybe you would like to  change that.

**Comment by dubrowgn** [comment]
If you open the app, it shows you how many amps the battery is getting from the charger. This will be somewhat less than the charger is giving to the phone, since the phone uses some, but I don't think android exposes charging current directly. Does that help, or were you asking for something else?

**Comment by teou1** [comment]
I think he is talking about the status bar. 

The paid version of Ampere already has this if you are willing to pay (as you will see in my screenshots, i just open both apps). Me personally, i like it that way. Ideal would be 1 App could show both W and A, but the space on the status bar is so limited...there is no way to squeeze both in 1 icon. So i'd leave it as it is (ampere shows amps, wattz shows watts...pretty logical?).
Of course some day in the future the developer of Wattz can make settings to choose from, and bloat the app with functions and ads, like Ampere. But who the hell needs 5 different ways to show the same info (yep i mean the ampere main screen). I personally like it simple and small like Wattz now.

As for the usb charging with type C and PD, there is a very nice chart from Texas Instruments explaining the specs. But the reality is, we still don't have 100W charging for phones. The maximum current is 3A in real life for a phone. And the theoretical 5v are also around 4 in reallity.

So for all practical purposes...one can just divide the Watts by 4 and get the A, as it is well seen on the screenshots. 
![Screenshot_20221001-044044](https://user-images.githubusercontent.com/10502326/193384437-162874c8-5e92-477c-a404-eb229ad6372f.png)
![Screenshot_20221001-034917](https://user-images.githubusercontent.com/10502326/193384438-19a056f4-1b57-490f-9142-cc0ca4a9f3ac.png)
![Screenshot_20221001-040209](https://user-images.githubusercontent.com/10502326/193384439-71feea79-dd4d-4bfa-9454-5eb15e2123ea.png)

**Comment by ulph0** [comment]
hi, i am very sorry, i was disoriented because wattz showed me a current draw of only -0,3A from my charger where i remembered had to be much more viewed with ampere. turned out that maybe sth happened to the cable, if i use a new cable, the phone draws 1,8 A. i installed ampere (from "braintrapp") for testing and wattz tells me exactly the same.

nevertheless the idea with the status bar above is good and also for readability the ampere layout is a good inspiration i think. i will attach a screenshot. take care and thanks for the app!

![ampere](https://user-images.githubusercontent.com/25482552/193428938-e41a9d93-09d9-48c3-b6f5-87e5e9001903.png)

**Comment by dubrowgn** [comment]
Thanks for the tip. I don't think I'll add a status indicator for amps, especially since there is another app for that. I did end up overhauling the app's layout in [0fc788e9b40480b7df7ed5d794da332351e4d83a](https://github.com/dubrowgn/wattz/commit/0fc788e9b40480b7df7ed5d794da332351e4d83a), which should help readability quite a bit. I'm no designer, but it's not too bad IMO ;)

Hopefully I'll have a new release cut in the next couple of days, but there are a few items I want to take care of first.

**Comment by ulph0** [comment]
hi, thank you that lookes much better! i don't really lunderstand what you do mean by "especially since there is another app for that. "?! ampere? really for me, an app from google play store is like no app since i don't like that google makes money out of its users data i don't use it. i just installed ampere to test your app. or is there another app which does that on f-droid?

**Comment by dubrowgn** [comment]
I was referring to ampere. Just out of curiosity, is there a reason you want to see amps instead of watts? Given that the USB-PD spec, as well as other specs like QuickCharge, operate at different voltages, just knowing amperage doesn't necessarily tell you how your charger is performing. Alternatively, watts naturally takes this into account. If you want to see a more detailed amp/volt breakdown, the app view already shows you this.

**Comment by ulph0** [comment]
> I was referring to ampere. Just out of curiosity, is there a reason you want to see amps instead of watts? Given that the USB-PD spec, as well as other specs like QuickCharge, operate at different voltages, just knowing amperage doesn't necessarily tell you how your charger is performing. 

the reason is its more practical/common. see this powerbank: https://src.discounto.de/pics/Angebote/2019-02/4597445_RealPower-PB-10000-mini-HD-Powerbank-schwarz_xxl.jpg - lots of powerbanks and chargers have the volts and amperes printed on it. some cheap gadgets like my e-cigarette take 'max 1A' - so mostly i have no watts and i don't like to calculate it in my head. in first place i needed to roughly check chargers / usb power supplies respectively cables what they are able deliver and if they are working as they should. 

> Alternatively, watts naturally takes this into account. If you want to see a more detailed amp/volt breakdown, the app view already shows you this.

the idea with the status bar was not by me. i thought it would be useful to have that as configurable option, since for me the watts are nearly useless, but i have no problem with first starting the app view. to be honest i personally don't need any value printed into the status bar. 

what i would like is a usb data cable speed test in your app, while i already accepted that that's not its purpose :)

btw. i am still using an old microUSB phone.

**Comment by ulph0** [comment]
hi, today i installed the new version from f-droid. lookes much nicer! it doesn't look really centered maybe because the text on the left side is shorter but i can live with that. unfortunately the app now doesn't shoow any watts or amperes to me.Current shows 0,0A, Power 0,0W. Energy -Wh (-Ah) when charging or discharging. when charging. Time to Full Charge also remains empty. Regards!

**Comment by ulph0** [comment]
ah okay. when i change the settings to mA i get values tp Current and Power, but still in A. if i change this to uA or nA they are again on 0.

**Comment by dubrowgn** [comment]
You're effectively selecting what units the phone reports battery current in, not the displayed units. This is a work around for incorrect `BatteryManager` implementations by your phone manufacture. If you get reasonable power numbers by selecting `mA` instead, it means your phone is incorrectly reporting current in `mA` instead of `uA` (as specified in the API spec).

**Comment by ulph0** [comment]
Ah ok sorry for misundertanding. "Energy" and "Time to full Charge" also fills after a while, "Energy" not yet. Thank you very much.

**Comment by teou1** [comment]
Jeez, that was a drastic overhaul. The font is much bigger and easy on the eyes now. Thanks.

**Comment by dubrowgn** [comment]
Release https://github.com/dubrowgn/wattz/releases/tag/v1.13 added a units setting for the status bar indicator. It should show up in F-Droid in the next few days. Google Play is a different story due to new changes to their publishing requirements, so no ETA there at the moment. I'm going to close this as resolved, but feel free to provide feedback. For the time being at least, I'm going to stick to one status bar indicator.
