### ISSUE TITLE
Exit button

### ISSUE THREAD

**Issue by teou1** [dubrowgn/wattz#17]
Hi, this is a fantastic app, but isn't it a bit stupid to have to force close every time? It would be nice to have a gracefull shutdown somehow.

As a side note: maybe you can make the font a bit bigger? And you can publish the apk also in the Playstore? Not a deal breaker but will be nice.

Best regards, Teo

**Comment by dubrowgn** [comment]
I'm glad you find it useful!

>  isn't it a bit stupid to have to force close every time

Are you referring to the app, or the status icon? If it's the former, I'm not aware of any app that has a "close" button. This is how android is designed to operate. If it's the latter, the status icon is intended to always be running (the status icon is the primary feature here). If you just want an app that tells you some battery info, there are other apps that already do that.

> maybe you can make the font a bit bigger

Are you referring to the app, or the status icon? The status icon has size constraints, but I'll keep it in mind for the app view. I would like to improve the app view, but haven't decided quite how yet. It's secondary to the status icon, so I haven't really spent any time making it look pretty yet.

> you can publish the apk also in the Playstore?

Getting a developer account capable of publishing on play store costs money. Since this is a hobby project, I haven't been willing to do that so far, but that may not always be the case.

**Comment by teou1** [comment]
I meant the running foreground service/ status icon. By many apps with such services you can for example exit the service with double click on the back button (1 click usually triggers the explanation "press home to minimize and leave running in background, press back again to completely exit"). But i got your point if this is by design.

About the font size i meant the main window. On a second thought not everybody has a high res display...not that you receive bug reports "text is too big and does not line wrap und is cut off at the edge of the screen" from people with low res devices. 

I didn't know Google charges for developer accounts...i thought it's worse enough they repackage and resign, and take a huge commision, and have too strict rules crippling apps...but to ask money for free apps without ads tops all.
If you have to fill the app with ads to pay for the account than i vote it down 👎

**Comment by paulle** [comment]
I would support using bigger fonts, it's better for people with bad eyes.

**Comment by dubrowgn** [comment]
I pushed a visual overhaul of the app in https://github.com/dubrowgn/wattz/commit/0fc788e9b40480b7df7ed5d794da332351e4d83a. It should improve readability in general, and I bumped the font size up a bit.

**Comment by paulle** [comment]
Thank you

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 3. Okt. 2022, 17:59, schrieb Dustin Brown :

**Comment by dubrowgn** [comment]
I just cut a new v1.9 release with the larger font. I'm closing this issue for now since the power indication is meant to run all the time. Thanks for the feedback!
