### ISSUE TITLE
[RFE] hide on charging / not charging

### ISSUE THREAD

**Issue by t184256** [dubrowgn/wattz#18]
I'm only interested in charging current and want to save notification space otherwise. I'd appreciate an option for hiding the icon on not charging or charging.

**Comment by dubrowgn** [comment]
Thanks for the feedback! I really want to keep wattz as simple as possible, so unfortunately this isn't a feature I'm interested in implementing at the moment. It would actually require a significant architecture shift as well, since a notification icon is required by android for all long running services that are running.
