### ISSUE TITLE
[Bug] Claiming "charging" with negative power amount

### ISSUE THREAD

**Issue by nsde** [dubrowgn/wattz#19]
Here's a screenshot:

![Screenshot_2022-10-06-17-58-49-481_dubrowgn.wattz.jpg](https://user-images.githubusercontent.com/67185896/194361700-ddc209e4-2925-4161-87f0-85eb40e953b9.jpg)

**Comment by dubrowgn** [comment]
Your phone is more than likely incorrectly reporting battery current with an inverted sign. v1.9 has a work around for this, which you will have to enable on the settings screen. v1.9 hasn't made it to F-Droid quite yet, but it should be available there within the next couple of days. Otherwise, you can install v1.9 from the releases page on this repo.

**Comment by dubrowgn** [comment]
Dupe of: https://github.com/dubrowgn/wattz/issues/12
