### ISSUE TITLE
ZUI系统状态栏不显示

### ISSUE THREAD

**Issue by gbxm** [dubrowgn/wattz#21]
已测试ZUI12-ZUI14 系统下使用此软件  状态栏仅显示为一个图标  ， 无动态功耗信息

**Comment by dubrowgn** [comment]
Which version are you using? When you say there is no power consumption information, are you saying it is always zero? Can you share a screenshot?

**Comment by gbxm** [comment]
![github](https://user-images.githubusercontent.com/68811102/195233642-162f8d84-0a5a-448f-b6b5-21b62559e1ea.jpg)
As shown, using the latest version of this software on ZUI system, the system taskbar only shows icons, no relevant dynamic power consumption information display

**Comment by dubrowgn** [comment]
Interesting. I haven't seen this before, but https://stackoverflow.com/questions/54821109/android-notification-small-icon-not-working-on-some-devices seems to indicate your phone may be trying to "fall back" to a higher resolution icon. Would mind giving this build a try, and letting me know if it resolves your issue? It dynamically calculates the icon size based on the display density, instead of using a hard coded size.

[wattz-1.10-a4818d7.zip](https://github.com/dubrowgn/wattz/files/9765945/wattz-1.10-a4818d7.zip)

**Comment by gbxm** [comment]
> Interesting. I haven't seen this before, but https://stackoverflow.com/questions/54821109/android-notification-small-icon-not-working-on-some-devices seems to indicate your phone may be trying to "fall back" to a higher resolution icon. Would mind giving this build a try, and letting me know if it resolves your issue? It dynamically calculates the icon size based on the display density, instead of using a hard coded size.
> 
> 有意思。我以前从未见过这种情况，但是 https://stackoverflow.com/questions/54821109/android-notification-small-icon-not-working-on-some-devices 似乎表明你的手机可能正试图“退回”到一个更高分辨率的图标。介意试一下这个版本吗? 如果它解决了你的问题，请告诉我？它根据显示密度动态计算图标大小，而不使用硬编码的大小。
> 
> [wattz-1.10-a4818d7.zip](https://github.com/dubrowgn/wattz/files/9765945/wattz-1.10-a4818d7.zip)
> 
> Wattz-1.10-a4818d7. zip

Unfortunately, the version you provide is the same, and still can not achieve dynamic power consumption information display in the status bar

**Comment by dubrowgn** [comment]
We can try rounding up to the next whole density to mirror the way android picks icon resolutions. Can you try this build?

[wattz-1.11-4c92b1a.zip](https://github.com/dubrowgn/wattz/files/9787566/wattz-1.11-4c92b1a.zip)

**Comment by Anonymous2716** [comment]
Just out of curiosity how does this affect the icon view?  

> It dynamically calculates the icon size based on the display density, instead of using a hard coded size.

**Comment by dubrowgn** [comment]
@Anonymous2716 Depending on your device's pixel density, the icon might be a bit more clear and easier to read. In the context of this issue, the device in question has a higher pixel density than the hard coded value would be associated with. I was hoping the device wasn't showing the correct icon because it was too low resolution, but that did not seem to be the case.

**Comment by dubrowgn** [comment]
I'm closing this for now as an upstream issue for now. @gbxm, if you get more info in the future, we can re-open this issue then.
