### ISSUE TITLE
About

### ISSUE THREAD

**Issue by harrischrisa** [dubrowgn/wattz#22]
It would be useful to have an "about" in the settings which indicated what the current version the app is.

**Comment by dubrowgn** [comment]
This is something android provides already. If you long touch an app icon, and press "info", the version should be at the bottom. You should also be able to find it via settings -> apps, or similar.

**Comment by harrischrisa** [comment]
Thanks.

The information is available via the android system but it would be useful to also see the version in Settings

13 Oct 2022 1:10:57 am Dustin Brown ***@***.***>:

**Comment by dubrowgn** [comment]
Thanks for the feedback, but for the sake of simplicity I don't think I'll add this. Android already provides the source of truth for this, and putting it on the settings view opens the possibility of introducing the an incorrect version number in the settings view. This is because the version number would need to be replicated there, and if the app version is ever updated without properly replicating it, the old version number will remain in the settings view.
