### ISSUE TITLE
Watts or mAh Selection

### ISSUE THREAD

**Issue by fluidicice** [dubrowgn/wattz#28]
Feature Request: A toggle to swap usage in Watts to usage in Milliamp hours.

Additional feature: If mAh is over 1,000, an option to display it in shortened form (-1.0K mAh)

Love the simplicity of the app, keep it up.

**Comment by dubrowgn** [comment]
Related: https://github.com/dubrowgn/wattz/issues/15, https://github.com/dubrowgn/wattz/issues/16.

I have been planning to make the indicator value selectable from any of the values in the main app screen, but I unfortunately haven't gotten around to it yet.

Regarding showing mAh, the indicator really only has enough space for about 2 digits since it is square and I can't make it wider. If I make the text small enough to fit more digits, it probably wouldn't be readable.

**Comment by dubrowgn** [comment]
You motivated me to finally take a look at implementing this.

Release https://github.com/dubrowgn/wattz/releases/tag/v1.13 added a units setting for the status bar indicator. It should show up in F-Droid in the next few days. Google Play is a different story due to new changes to their publishing requirements, so no ETA there at the moment. Feel free to try it out and let me know if that is at all what you were looking for.
