### ISSUE TITLE
Add PLUGGED information.

### ISSUE THREAD

**Issue by Anonymous2716** [dubrowgn/wattz#32]
Such as :
```
PLUGGED_AC
PLUGGED_USB
PLUGGED_WIRELESS
```

Is helpful information.

**Comment by dubrowgn** [comment]
It would be doable, but can you describe your usecase? I previously decided against it because I couldn't come up with a usecase where it wasn't largely redundant info. For example, I already know that it's charging via USB because I physically plugged it into USB.

**Comment by Anonymous2716** [comment]
Its more of a trouble shooting issue. For example I was having some issues with the USB port on my phone. sometimes I see its plugged in as USB and other times AC. When it is plugged in as USB its barely charging. Pulls something over 1 Watt at 4 volts. And when over AC it goes up to 6 Watts.

**Comment by Anonymous2716** [comment]
Its entirely up to you whether you want to add or not.

**Comment by dubrowgn** [comment]
Makes sense. I'll take a look when I have some time.

**Comment by dubrowgn** [comment]
This was added in 0c07292096e42b93cee2b568d27b39e67cd0947e.

**Comment by dubrowgn** [comment]
This was released in [v1.18](https://github.com/dubrowgn/wattz/releases/tag/v1.18). You can get it from the releases page, or F-Droid and Play Store should pick it up in the next few days.

Feel free to re-open this issue if the release doesn't resolve your concern.

**Comment by Anonymous2716** [comment]
@dubrowgn Nice thanks.

**Comment by ebbi2017** [comment]
That's a very nice feature.

I mainly use Wattz to check my aging battery (show voltage while not loading).
Because my phone decides to show like 50+ % capacity even when it's battery is at 3.3 V only, f.e., shortly before going off.
I tried battery calibration tools, but none did work sadly, so the % stays inaccurate, while the runtime is like 3 hours with screen on still.
With Wattz I can see and decide when to shut down manually or load again.

Now it would be nice to have the possibility to show both V and W optionally.
I also have different cables, chargers and wanna see if it's loading with 0.5 A or more like 1.8 A, f.e. (which is maximum for my phone). This f.e. is needed in the car / on the bike when navigation is on and the battery drain usually is much higher than loading with the wrong cable (too much resistance, not only length is important! I have many long cables which are better than short ones also) or low amp chargers.

Thx for this great app!
