### ISSUE TITLE
[Feature Request] Battery Percentage

### ISSUE THREAD

**Issue by derei** [dubrowgn/wattz#39]
Before you all jump on me to say this feature is already implemented in Android, please hear me out:
The Android native Battery Percentage is linked to the Battery icon. Meaning that disabling the icon will unavoidably disable the %.
I personally don't care much about the battery icon, but I'd like to see only a percentage in the status bar.

I'm wondering if the dev would be interested to add this as a feature.

Also, is it an Android thing that regular apps show their icons on the left side of the status bar? Would it be possible to display it on the right side?

Thanks.

**Comment by dubrowgn** [comment]
It would be possible to add level of charge in percent to the app. I hadn't done so because users generally already have it available through the system battery icon, as you said.

As for the icon being on the left side, this is an Android implementation thing. As far as I know, apps don't have access to the actual status bar. Wattz emulates something similar with a persistent notification, and notifications go on the left side. If anyone knows any differently, I would love to hear about it.

**Comment by derei** [comment]
I believe you are right about notificatoon bar. Any other app showing an icon there, is acting like a notification.

In the meantime, I opted to a different solution: Using your app to monitor power, and an app called PowerLine to display charging level. Is a visual display (a line that varies in length according to battery charging level). Is less precise than %, but is pretty useful at ballparking the remaining battery charge.

So, I guess, this two aspects being cleared:
- that the icon can't be shown to the far right, due to Android limitations
- a suitable workaround has been found to replace battery icon and %

I believe my feature request became redundant. Thank you for being so kind and help me understand the limitations.

**Comment by dubrowgn** [comment]
Charge level info was added in [v1.19](https://github.com/dubrowgn/wattz/releases/tag/v1.19)
