### ISSUE TITLE
Power scalar workaround greater freedom of choice 

### ISSUE THREAD

**Issue by GremlineQ** [dubrowgn/wattz#44]
I don't know if it would work in a good way, but I have a Samsung phone (yes, I read that Samsung does it differently, but that's not what I'm talking about here) I have a charger that shows me how many watts my phone consumes, the error is about -2W at x1000 and I was wondering if it could be possible to add a window in which the user would enter his own multiplier or something similar.

**Comment by dubrowgn** [comment]
One thing to keep in mind is "battery power" (that Wattz reports) is different than "charger power", which your charger or an external power meter would report. This is because your phone consumes power that never makes it into the battery, as well as the fact that charging is a lossy process. See also, [the faq](https://github.com/dubrowgn/wattz?tab=readme-ov-file#faq). Basically, both power meters are correct, just measuring different things.

**Comment by GremlineQ** [comment]
sorry, I forgot that the measurement on the phone is on something else, thank you and I completely forgot about this report
